services:
  otrs:
    image: otrs:latest
    container_name: otrs
    hostname: otrs
    ports:
      - "8080:80"
      - "8443:443"

  mariadb:
    image: mariadb:10
    container_name: mariadb
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 23e117b59bf1d
      MARIADB_USER: otrs
      MARIADB_PASSWORD: 23e117b59bf1d
      MARIADB_DATABASE: otrs
    volumes:
      - ./mariadb.cnf:/etc/mysql/conf.d/otrs.cnf
